### ISSUE TITLE
UI runtime

### ISSUE THREAD

**Issue by malware-dev** [malware-dev/MDK-Mockups#2]
Make a UI application to display runtime information, potentially allowing certain runtime edits for testing purposes.

**Comment by baratgabor** [comment]
From my limited testing with the console version, the features I'd see being particularly useful are:

- TextPanel visualization,
- PB Echo output,
- property outputs pertaining to a specific block (e.g. piston, rotor - to monitor their state),
- Runtime info output (if LastRunTimeMs can be implemented meaningfully),
- a generalized output to show all changes taking place on the grid at one place,
- error info about failed mock-specific method calls (e.g. trying to trigger non-existing PB), but this could be also in the generalized output,
- "command" (or cockpit hotbar) simulation support to run specific PB blocks with a specific parameter.

*[I realized meanwhile that the section below might be irrelevant / unfeasible if we go with the Presenter model Malware mentioned on Discord, since that relates to the visualization style as well.]*

With the exception of the generalized output, I think it would be a reasonable design to let users add multiple instances of these outputs types, connected to different underlying blocks.

For example, the user could select "TextPanel Visualization", then select a TextPanel block, and the visualization would appear on the canvas. Then they would do the same again to display another visualization instance for another TextPanel block. Also, they could add a generic property output visualization in a similar manner about e.g. a piston block that's being controlled, to monitor what's happening to it.

These visualizations could support dragging and snapping (possibly resizing too), and the created display configuration could be saved for subsequent runs of the app.

Or do you think something like this would be too complicated to implement? I'm just thinking about what would be comfortable for me personally, and assuming it would translate well to other scripters; but I might be totally wrong about it.

*[/section]*

Another thing I'd consider generally important about the design:

- Not to base it around any specific PB, but emphasize that we are simulating a grid, which can contain multiple PBs. Because, with the console version I had the feeling that it's largely based around a single PB in mind.
- We probably shouldn't try to display all TextPanels and PB Echo outputs automatically at startup, because with the support of blueprint loading, a lot of users might end up loading relatively large ships with dozens of TextPanels and PBs. But maybe we could make it conditional, to account for the cases where there is only 1-2 TextPanels and a single PB, and it can be reasonably assumed that the user will want to see these.

**Comment by malware-dev** [comment]
I would suggest _no_ automatic displays. I think the _most important aspect_ of the UI application would be a well-presented system for selecting and enabling visualizers for blocks, using search functions - of course keeping in mind that there might be large blueprint with _lots_ of terminal blocks involved. There should perhaps be the concept of a "project" or "workspace" that can be saved, which contains both a blueprint and the visualizing setup for that blueprint.

**Comment by baratgabor** [comment]
I also think it's best to go without automatic displays, and the search-centered UI sounds like a very good idea to me (i.e. if we do this, it should really scale well to large blueprints too).

But I'll need to get a handle on this Presenter-based visualization. :) If the Presenters are per data type (and not block type), how would that give a coherent presentation/visualization for a concrete block type, like a TextPanel or a Rotor? The resulting block type specific view/visualization would simply go through all properties of the block, and assemble the visualization by transforming each property with the relevant presenter? So the string content of the TextPanel could transform into a screen simulation, the float Angle of the rotor could transform into slider or bar, etc.?

Maybe some simple example would help me to understand.

**Comment by malware-dev** [comment]
All you really need to know for now is that the presenter system will provide you with a view that represents the given block. Leave the rest to me. I don't know when I can get around to make this, I need to route all available project time to MDK bugfixes first.

**Comment by baratgabor** [comment]
Cool. :) No hurries; I can just start working on it once you're done. Meanwhile I'll also try to finish my menu handler script at least.

**Comment by malware-dev** [comment]
You don't really _need_ to wait for me. There's plenty of work to do without actually having the block renderers. Just use a placeholder view for the blocks in the mean time.

**Comment by kwilliams1987** [comment]
This is implemented in the MDK-UI project added to the new [mockup-ui](https://github.com/malware-dev/MDK-Mockups/tree/mockup-ui) branch.
